name: PlayerQuests
description: ${project.description}
api-version: '1.20'
website: ${project.url}

author: sammypanda
version: ${project.version}

main: playerquests.Core

commands:
  playerquests:
    description: Opens the PlayerQuests menu.
    usage: /<command>
    aliases: [quest, pq]
  
  action:
    description: Working with quest actions.
    usage: /<command> <start|stop>
    aliases: [a]
