name: PlayerQuests
description: ${project.description}
api-version: '1.21'
website: ${project.url}

author: sammypanda
version: ${project.version}

main: playerquests.Core

softdepend: [Citizens]

commands:
  playerquests:
    description: Opens the PlayerQuests menu.
    usage: /<command>
    aliases: [quest, pq]

  action:
    description: Working with quest actions.
    usage: /<command> <start|stop>
    aliases: [a]
  
  test:
    description: Run developer tests.
    usage: /<command> <module>
    aliases: [t]
